name: Benchmarks

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build benchmarks
        run: |
          cargo bench --no-run --features sqlite

      - name: Run benchmarks
        run: |
          cargo bench --features sqlite

      - name: Generate overview
        run: |
          cargo xtask generate-benchmark-overview
        env:
          ENVIRONMENT: Github Actions

      - name: Deploy Docs
        if: ${{ github.ref == 'refs/heads/main'  }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/criterion/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /benchmarks/
          clean: true
